### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by xbmcnut** [benleb/surepetcare#13]
Not quite sure how to create a pull request but it might pay to let people know that if they follow your instructions and remove the surepercarebeta integration and replace it with the sureha one, all references to the service `surepetcarebeta.set_lock_state` will need to be changed manually to `sureha.set_lock_state`.

**Comment by benleb** [comment]
ah really nice catch 👍 thanks!

doing a PR for this (simple) change should be easy! You can even do it in the browser here [edit README.md](https://github.com/benleb/surepy/edit/dev/README.md)

so if you want to try, I am happy to assist if needed ;) if not, I will fix it 👍

Thanks @xbmcnut
