### ISSUE TITLE
Microchip Pet Door Battery Sensor needs some tuning

### ISSUE THREAD

**Issue by SamboyCoding** [benleb/surepetcare#14]
The battery sensor for the Sure Petcare [Microchip Pet Door](https://www.surepetcare.com/en-gb/pet-doors/microchip-pet-door) needs some tuning - the app has just sent me a Low Battery warning (so it's on about 10%, I guess?) and this integration is reporting... -16%. Which is obviously wrong.

Attached is a screenshot showing the reported voltage per battery and total voltage.

It is interesting though that the graph shows the percentage dropping from 44% at 06:04 this morning to -16% at 11:46, with no data points in between.

![image](https://user-images.githubusercontent.com/7011721/128597934-1a9818f9-5d86-42cf-ad25-5f84fa920edb.png)

**Comment by benleb** [comment]
Hey, yes thats a point where I would need some help as I cannot make sense from the battery data of the various devices... I will post additional info here the next days!

**Comment by matt-cahill** [comment]
Hi I'm willing to help, I have a cat flap with rechargeable batteries so adjusting the voltage levels is a great feature for me. Since 0.4.2 though I get `unknown` for the battery sensor state. Let me know if you want a separate issue for this?

![image](https://user-images.githubusercontent.com/2563358/134791026-b105cde3-35b1-4ae1-9287-d0590e10cf16.png)

**Comment by xbmcnut** [comment]
Mine came right after an hour or so. What batteries are you using?

**Comment by matt-cahill** [comment]
Panasonic Eneloop Pro. I've had 0.4.2 installed for a few days and it hasn't come right, even after a restart and fiddling around with the voltage settings a bit and removing and re-installing the integration.

``` 
Entity:  sensor.cat_flap_side_door_battery_level
State: unknown

State attributes (YAML, optional)
battery_level: 45
voltage: '5.53'
voltage_per_battery: '1.38'
unit_of_measurement: '%'
friendly_name: Cat Flap Side door Battery Level
device_class: battery
```

**Comment by jumpingmushroom** [comment]
> Panasonic Eneloop Pro. I've had 0.4.2 installed for a few days and it hasn't come right, even after a restart and fiddling around with the voltage settings a bit and removing and re-installing the integration.
> 
> ```
> Entity:  sensor.cat_flap_side_door_battery_level
> State: unknown
> 
> State attributes (YAML, optional)
> battery_level: 45
> voltage: '5.53'
> voltage_per_battery: '1.38'
> unit_of_measurement: '%'
> friendly_name: Cat Flap Side door Battery Level
> device_class: battery
> ```

+1 on this. I'm experiencing similar issues on both the water pond and the cat flap. In my case I'm using generic panasonic batteries on the cat flap and energizer batteries on the pond.

**Comment by retoziegler** [comment]
Same issue here: since updating to latest version the battery sensor shows unknown, although in the attributes it shows the correct battery level (pet flap):
![image](https://user-images.githubusercontent.com/56159492/136022185-954013ec-c514-4a5f-bdd5-462fd1c733c7.png)

**Comment by xbmcnut** [comment]
Even though my battery sensor is working, seems there is a glitch between the main value and the attribute value. This creates a problem for my https://github.com/maxwroc/battery-state-card as it's reporting the attribute value instead of the entity one.

![image](https://user-images.githubusercontent.com/1492137/137233845-0744fbe6-1864-48a4-8eea-70c0c50a6679.png)

**Comment by totalitarian** [comment]
Same issue here. Battery showing as unknown.

**Comment by xbmcnut** [comment]
Hey Ben,

I mistakenly removed my integration over the weekend and reinstalled (due the server error at Sure). After re-installation, I now get what other people are reporting and that's the lack of battery level. I have '''battery_level```  attributes but the main sensor reports unknown now. Is this something you are aware of?

![image](https://user-images.githubusercontent.com/1492137/152911154-112e21cc-3ccc-4975-8597-99d8c1136d2c.png)

Running SureHA v0.4.2 and HA 2022.02.03

**Comment by netphantm** [comment]
I used to see the same as @xbmcnut, but I also recently reinstalled SureHA and now I see this:

![image](https://github.com/benleb/sureha/assets/4569298/c13c9044-e1ee-4239-8495-34fafb7ad0b6)

surepet shows about half:

![image](https://github.com/benleb/sureha/assets/4569298/45a888f7-17db-4742-bb49-4b7f7ba9b52d)

I run it with a SureFLAP Connect (with hub)
