### ISSUE TITLE
Felaqua not showing actual weight.

### ISSUE THREAD

**Issue by blair287** [benleb/surepetcare#15]
Was working ok but updated to latest release now when I filled up it's not showing it.

You can see in attributes that actual weight is over 1000 but remaining shows previous amount.

![Screenshot_20210814-222945](https://user-images.githubusercontent.com/44187409/129460553-dc9a146f-3601-4390-a35f-1872b0a81c7b.png)
![Screenshot_20210814-222930](https://user-images.githubusercontent.com/44187409/129460556-b311c978-ecba-431b-a8d4-2b5832f82b0f.png)
![Screenshot_20210814-222952](https://user-images.githubusercontent.com/44187409/129460558-bd3727af-07d9-4185-bf0a-c0ad8d0d5633.png)

**Comment by blair287** [comment]
It did update eventually but took over 30inutes has the polling rate been changed?

**Comment by blair287** [comment]
As far as I can tell this is only effects the felaqua but updates seem to take 20-40 minutes to show up but pet attributes show up quite quickly that they drank.

You can see that 19ml was drank at 22:27 but it wasn't until 22:45 that change showed up times are -1 hour from phone time.

![Screenshot_20210814-234717](https://user-images.githubusercontent.com/44187409/129462050-11d50f76-e69a-4e5d-b246-c1021bccb909.png)
![Screenshot_20210814-234724](https://user-images.githubusercontent.com/44187409/129462051-3ed4c99d-95b6-49cb-a520-4054c3894861.png)

**Comment by blair287** [comment]
@benleb  looks like it's not looking at actual_weight as that number is changing but it's looking at weight which doesn't change when someone has a drink but it does know who.

Think it's best to use the actual weight for the sensor.

**Comment by benleb** [comment]
hey, please try again with [v0.2.3](https://github.com/benleb/sureha/releases/tag/v0.2.3), I think everything should be working now. If not, please open another issues (but I think if there's a problem, its a new one :D)
