### ISSUE TITLE
v2.x fails to call service

### ISSUE THREAD

**Issue by xbmcnut** [benleb/surepetcare#17]
Just upgraded to v2.0 and then v2.1 and now get the following error (on both versions):
```
2021-09-07 15:10:57 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: value must be one of [] for dictionary value @ data['flap_id']
2021-09-07 15:10:57 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140400169379200] Error handling message: value must be one of [] for dictionary value @ data['flap_id']. Got None
```

Here is the service I tried which is affecting my switches used to lock and unlock the door. Rolling back to the dev version (d434161) fixes it.

```
service: sureha.set_lock_state
data:
  flap_id: 7xx35xx
  lock_state: unlocked
```
Going to try switching now to the main HA version to see what happens.

**Comment by xbmcnut** [comment]
Tested [HA Sure Petcare](https://www.home-assistant.io/integrations/surepetcare/) via YAML integration and that is [not working either](https://github.com/home-assistant/core/issues/55884). Fails to create the door sensor. Staying on d434161 for now as that is fully working. Lucky I took backups!!

**Comment by benleb** [comment]
I will take a look, sorry 👍

Btw., don't worry about getting  old versions, they stay in my/the home assistant repo and/or also on pypi (surepy lib) 😊

**Comment by benleb** [comment]
sorry, I broke the condition of allowed values... Can you confirm it works with the current `dev` branch?

**Comment by xbmcnut** [comment]
Will do. I'll try 2.1 later today and report back. This one?

![image](https://user-images.githubusercontent.com/1492137/132420208-e44a1877-5d86-444d-9a2b-4dda7b5118b4.png)

**Comment by benleb** [comment]
refresh and update to [v0.2.2](https://github.com/benleb/sureha/releases/tag/v0.2.2) 👍

**Comment by xbmcnut** [comment]
See it now, thank you. Are you aligning the dev version with the HA version?

**Comment by benleb** [comment]
I would like to but... it's complicated ;) Home assistant won't accept a switch from the old, broken surepetcare to the sureha version in one big PR and don't have to the and also the will to split it to 5-15 smaller PRs. Splitting it up is a lot of work as every single PR done must basically be a working version of the integration which means touching the same code parts all over the integration, again and again, to make everything work with the current of XX PRs... I am in contact with @Danielhiversen and I think I also reach out to @MartinHjelmare to find a solution for this mess (which is initially my fault, not HAs!)

**Comment by xbmcnut** [comment]
Thanks for the feedback. Seems like a big job! I can confirm that v2.3 is working as expected with the `sureha.set_lock_state` fully functional again and the door sensor showing the correct state. Feel free to close this bug report.

**Comment by benleb** [comment]
Btw., @Danielhiversen did [a lot of work](https://github.com/home-assistant/core/pulls?q=+is:pr+label:%22integration:+surepetcare%22) in the last few days on the integration, implementing a lot of stuff from sureha, I added the felaqua today...  👍
