### ISSUE TITLE
Statuses not updating

### ISSUE THREAD

**Issue by blair287** [benleb/surepetcare#2]
Great work on this custom component!

The lock is back and the services are working but the status of cats, batteries, locks etc only update on HA server restart they don't ever update on their own.

Cheers

**Comment by benleb** [comment]
hey blair, sorry it took some days :/

pushed new code seconds ago, try again please :) if something is not working, please enable the debug logging (how to do this is noted in the readme now :))

**Comment by blair287** [comment]
> hey blair, sorry it took some days :/
> 
> pushed new code seconds ago, try again please :) if something is not working, please enable the debug logging (how to do this is noted in the readme now :))

Updated but get this error if I change my config to surepetcarebeta.

![Screenshot_20210509-164258](https://user-images.githubusercontent.com/44187409/117578330-bb38e700-b0e5-11eb-9edf-9ad85b2e381b.png)

**Comment by benleb** [comment]
ok I found the problem, the surepy releases I did today are all just 8 bytes in size... worked locally as I use a dev version that is not installed via pip -.-^ give me some minutes

**Comment by benleb** [comment]
hm ok, can reproduce this... but not yet sure why it happens :D

**Comment by benleb** [comment]
ok, seems gone with the current code and a completely new setup.... can you confirm this? From my feeling I would say cleaning up everything related to the non-beta was the key... but don't really know...^^

**Comment by benleb** [comment]
probably fixed :) see #3 :)

**Comment by blair287** [comment]
> probably fixed :) see #3 :)

Yep all working now nice one!
