### ISSUE TITLE
Pet flap entity

### ISSUE THREAD

**Issue by matt-oneill** [benleb/surepetcare#20]
Can the cat flap/pet flap have an entity to be able to get its current status. 
locked_in, locked_out etc

**Comment by xbmcnut** [comment]
That's already available in this variant. `sensor.pet_flap_laundry_door` in my case

**Comment by matt-oneill** [comment]
I only have battery level and connectivity entities

**Comment by xbmcnut** [comment]
> I only have battery level and connectivity entities

Are you running sureha or the Home assistant add-on version?  The HA version is currently broken and the door sensor is not working.

**Comment by matt-oneill** [comment]
After a few times removing and adding the integration is has appeared. No errors in the logs. 

> > I only have battery level and connectivity entities
> 
> Are you running sureha or the Home assistant add-on version? The HA version is currently broken and the door sensor is not working.

After a few times removing and adding the integration is has appeared. No errors in the logs. I couldn’t get the Home Assistant add on to work at all before trying this one
