### ISSUE TITLE
SureHA won't load in 2023.2.x

### ISSUE THREAD

**Issue by xbmcnut** [benleb/surepetcare#38]
FYI, I had an issue after upgrading to 2023.2.2 which I fixed just by re-adding another instance of SureHA and putting in my username and password again. For a brief second I had two instances of SureHA and then the 2nd one disappeared and the main one started working again.

**Comment by xbmcnut** [comment]
Just posted for others who may have seen the issue too.

**Comment by Unfocused** [comment]
If this was shown as an authentication issue in the integrations list, then I just had the same & with the same fix. But I haven't upgraded HA to 2023.2 yet - I'm still on 2023.1.7.

**Comment by xbmcnut** [comment]
To be fair, when I did try and debug and logged in [here](https://surepetcare.io/auth/login) to see if the servers were up, the site asked me to agree to new terms of service to proceed so maybe that was the issue all along?

**Comment by Unfocused** [comment]
I think that'd make sense.

**Comment by bscheutjens** [comment]
Thanks for this. Earlier today the integration stopped working for me (nothing changed). A restart of HA didn't help and in the logging I saw an authentication error. After reading this I deleted the integration, added it and now everything works again. I also logged in to their website, but didn't have to agree to new terms and conditions.
