### ISSUE TITLE
Device tracker

### ISSUE THREAD

**Issue by jasperbom** [benleb/surepetcare#9]
Not sure if this is the right place.... 

Would be nice if the presence of the pet could be a Device_tracker. In this way could be linked as a person (badge)

**Comment by xbmcnut** [comment]
Under the current beta, if you add the binary_sensor.pet_xxx as an entity card, it will show you a picture of the pet and show them as either Home or Away. Furthermore, you can use the custom component for the [composite device tracker](https://github.com/pnbruckner/ha-composite-tracker) to make a person for your pet/s.

https://community.home-assistant.io/t/sureflap-connect-pet-door/41488/386

**Comment by benleb** [comment]
a "real" one is wip [here](https://github.com/benleb/sureha/blob/dev/device_tracker.py) but its not really usable yet

**Comment by benleb** [comment]
[v0.4.0](https://github.com/benleb/sureha/releases/tag/v0.4.0) 👀 🕵️‍♀️
